// data/instituteData.ts

import { Institute } from "../../../types/Institute";

export const instituteData: Institute[] = [
  {
    id: 1,
    name: 'ABC Engineering College',
    code: 'ABC-ENG-001',
    type: 'Engineering',
    address: '123 Tech Street',
    city: 'Bangalore',
    state: 'Karnataka',
    pincode: '560001',
    country: 'India',
    phone: '+91-80-25555555',
    email: 'info@abceng.edu.in',
    website: 'www.abceng.edu.in',
    principalName: 'Dr. Rajesh Kumar',
    principalContact: '+91-9876543210',
    establishedYear: '1995',
    affiliation: 'VTU',
    campusArea: '25 acres',
    status: 'Active'
  },
  {
    id: 2,
    name: 'XYZ Medical College',
    code: 'XYZ-MED-002',
    type: 'Medical',
    address: '456 Health Avenue',
    city: 'Mumbai',
    state: 'Maharashtra',
    pincode: '400001',
    country: 'India',
    phone: '+91-22-26666666',
    email: 'admin@xyzmed.edu.in',
    website: 'www.xyzmed.edu.in',
    principalName: 'Dr. Sunita Sharma',
    principalContact: '+91-9876543211',
    establishedYear: '1980',
    affiliation: 'MUHS',
    campusArea: '30 acres',
    status: 'Active'
  },
  {
    id: 3,
    name: 'PQR Business School',
    code: 'PQR-BUS-003',
    type: 'Business',
    address: '789 Commerce Road',
    city: 'Del极速加速器',
    state: 'Delhi',
    pincode: '110001',
    country: 'India',
    phone: '+91-11-27777777',
    email: 'info@pqrbs.edu.in',
    website: 'www.pqrbs.edu.in',
    principalName: 'Dr. Amit Verma',
    principalContact: '+91-9876543212',
    establishedYear: '2005',
    affiliation: 'AICTE',
    campusArea: '15 acres',
    status: 'Inactive'
  },
  {
    id: 4,
    name: 'LMN Arts and Science College',
    code: 'LMN-ART-004',
    type: 'Arts & Science',
    address: '101 Culture Street',
    city: 'Chennai',
    state: 'Tamil Nadu',
    pincode: '600001',
    country: 'India',
    phone: '+91-44-28888888',
    email: 'contact@lmnarts.edu.in',
    website: 'lmnarts.edu.in',
    principalName: 'Dr. Priya Iyer',
    principalContact: '+91-9876543213',
    establishedYear: '1975',
    affiliation: 'Anna University',
    campusArea: '20 acres',
    status: 'Active'
  },
  {
    id: 5,
    name: 'RST Law College',
    code: 'RST-LAW-005',
    type: 'Law',
    address: '202 Justice Avenue',
    city: 'Kolkata',
    state: 'West Bengal',
    pincode: '700001',
    country: 'India',
    phone: '+91-33-29999999',
    email: 'admin@rstlaw.edu.in',
    website: 'www.rstlaw.edu.in',
    principalName: 'Dr. Sanjay Chatterjee',
    principalContact: '+91-9876543214',
    establishedYear: '1990',
    affiliation: 'BCI',
    campusArea: '10 acres',
    status: 'Active'
  }
];